storage:
  type: legacy
  database:
    type: pickleddb
    # TODO: Would be nice to be able to interpolate the experiment working dir in here:
    # host: runs/{exp.working_dir}/orion_db.pkl
    host: runs/gpt2_wikitext103/orion_db.pkl
    timeout: 300

experiment:
  algorithms:
    random:
      seed: 123
  max_broken: 999
  max_trials: 1000

evc:
  enable: True
  algorithm_change: False
  auto_resolution: True
  cli_change_type: break
  code_change_type: break
  config_change_type: break
  orion_version_change: False
  ignore_code_changes: False
  manual_resolution: True
  non_monitored_arguments: []
