storage:
  type: legacy
  database:
    type: pickleddb
    host: orion_db.pkl

experiment:
  algorithms:
    random:
      seed: 123
  max_broken: 999
  max_trials: 1000

evc:
  enable: True
  algorithm_change: False
  auto_resolution: True
  cli_change_type: break
  code_change_type: break
  config_change_type: break
  orion_version_change: False
  ignore_code_changes: False
  manual_resolution: True
  non_monitored_arguments: []
